/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "rnreanimatedJSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeReanimatedModuleCxxSpecJSI_installTurboModule(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeReanimatedModuleCxxSpecJSI *>(&turboModule)->installTurboModule(
    rt
  );
}

NativeReanimatedModuleCxxSpecJSI::NativeReanimatedModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("ReanimatedModule", jsInvoker) {
  methodMap_["installTurboModule"] = MethodMetadata {0, __hostFunction_NativeReanimatedModuleCxxSpecJSI_installTurboModule};
}
static jsi::Value __hostFunction_NativeReaWorkletsModuleCxxSpecJSI_installTurboModule(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeReaWorkletsModuleCxxSpecJSI *>(&turboModule)->installTurboModule(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt)
  );
}

NativeReaWorkletsModuleCxxSpecJSI::NativeReaWorkletsModuleCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("WorkletsModule", jsInvoker) {
  methodMap_["installTurboModule"] = MethodMetadata {1, __hostFunction_NativeReaWorkletsModuleCxxSpecJSI_installTurboModule};
}


} // namespace facebook::react
