
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <reanimated/android/view/react/renderer/components/rnreanimated/EventEmitters.h>
#include <reanimated/android/view/react/renderer/components/rnreanimated/Props.h>
#include <reanimated/android/view/react/renderer/components/rnreanimated/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>
#include <react/renderer/core/LayoutContext.h>

namespace facebook::react {

JSI_EXPORT extern const char ReanimatedViewComponentName[];

/*
 * `ShadowNode` for <ReanimatedView> component.
 */
using ReanimatedViewShadowNode = ConcreteViewShadowNode<
    ReanimatedViewComponentName,
    ReanimatedViewProps,
    ReanimatedViewEventEmitter,
    ReanimatedViewState>;

class ReanimatedViewCustomShadowNode final : public ReanimatedViewShadowNode {

public:
    using ConcreteViewShadowNode::ConcreteViewShadowNode;

    void layout(LayoutContext layoutContext) override {
//        YogaLayoutableShadowNode::layout(layoutContext);
    }

};

} // namespace facebook::react
