
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include <reanimated/android/view/react/renderer/components/rnreanimated/ShadowNodes.h>
#include <react/renderer/core/LayoutContext.h>

namespace facebook::react {

extern const char ReanimatedViewComponentName[] = "ReanimatedView";

} // namespace facebook::react
