'use strict';
import {
  registerWebSvgPropsBuilder,
  SVG_CIRCLE_WEB_PROPERTIES_CONFIG,
  SVG_ELLIPSE_WEB_PROPERTIES_CONFIG,
  SVG_IMAGE_WEB_PROPERTIES_CONFIG,
  SVG_LINE_WEB_PROPERTIES_CONFIG,
  SVG_LINEAR_GRADIENT_WEB_PROPERTIES_CONFIG,
  SVG_PATH_WEB_PROPERTIES_CONFIG,
  SVG_PATTERN_WEB_PROPERTIES_CONFIG,
  SVG_POLYGON_WEB_PROPERTIES_CONFIG,
  SVG_POLYLINE_WEB_PROPERTIES_CONFIG,
  SVG_RADIAL_GRADIENT_WEB_PROPERTIES_CONFIG,
  SVG_RECT_WEB_PROPERTIES_CONFIG,
  SVG_TEXT_WEB_PROPERTIES_CONFIG,
} from './web';

export function initSvgCssSupport() {
  registerWebSvgPropsBuilder('Circle', SVG_CIRCLE_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder('Ellipse', SVG_ELLIPSE_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder('Image', SVG_IMAGE_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder('Line', SVG_LINE_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder(
    'LinearGradient',
    SVG_LINEAR_GRADIENT_WEB_PROPERTIES_CONFIG
  );
  registerWebSvgPropsBuilder('Path', SVG_PATH_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder('Pattern', SVG_PATTERN_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder('Polygon', SVG_POLYGON_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder('Polyline', SVG_POLYLINE_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder(
    'RadialGradient',
    SVG_RADIAL_GRADIENT_WEB_PROPERTIES_CONFIG
  );
  registerWebSvgPropsBuilder('Rect', SVG_RECT_WEB_PROPERTIES_CONFIG);
  registerWebSvgPropsBuilder('Text', SVG_TEXT_WEB_PROPERTIES_CONFIG);
}
