compressionLevel: mixed

defaultSemverRangePrefix: ''

enableConstraintsChecks: true

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 8d

npmPreapprovedPackages:
  - 'expo'
  - 'react'
  - '@react-native/*'
  - 'react-native'
  - 'react-native-web'
  - 'react-native-macos'
  - 'react-native-tvos'
  - 'react-native-reanimated'
  - 'react-native-worklets'
  - 'react-native-gesture-handler'
  - 'react-native-screens'
  - 'babel-plugin-syntax-hermes-parser'
  - 'hermes-parser'
  - 'hermes-estree'

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.13.0.cjs
