compressionLevel: mixed

# defaultSemverRangePrefix: ""

# enableConstraintsChecks: true

enableGlobalCache: false

nodeLinker: node-modules

# npmMinimalAgeGate: 6000
# npmPreapprovedPackages:
#   - "react"
#   - "react-native"
#   - "@react-native/*"
#   - "react-native-gesture-handler"
#   - "react-native-screens"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
