compressionLevel: mixed

defaultSemverRangePrefix: ''

enableConstraintsChecks: true

enableGlobalCache: false

nodeLinker: node-modules

#  TODO: Uncomment `npmMinimalAgeGate` and `npmPreapprovedPackages`
# after we can bump to Yarn 4.10, currently blocked by a bug
# https://github.com/yarnpkg/berry/issues/6944
# npmMinimalAgeGate: 6000
# npmPreapprovedPackages:
#   - 'react'
#   - 'react-native'
#   - '@react-native/*'
#   - 'react-native-gesture-handler'
#   - 'react-native-screens'

tsEnableAutoTypes: false

yarnPath: .yarn/releases/yarn-4.1.1.cjs
