name: Java Lint
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - '.github/workflows/validate-java.yml'
      - 'android/src/main/java/**'
      - 'android/build.gradle'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-java.yml'
      - 'android/src/main/java/**'
      - 'android/build.gradle'

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: validate-java-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Clear annotations
        run: scripts/clear-annotations.sh

      - name: Install node dependencies
        run: yarn
      - name: Lint
        run: yarn lint:java
