import {
  chromeDebuggerHermesAndroid,
  chromeDebuggerHermesiOS,
  chromeDebuggerHermesWeb,
  chromeDebuggerJSCAndroid,
  chromeDebuggerJSCiOS,
  chromeDebuggerJSCWeb,
  chromeDebuggerV8Android,
  chromeDebuggerV8iOS,
  chromeDebuggerV8Web,
  chromeDevToolsHermesAndroid,
  chromeDevToolsHermesiOS,
  chromeDevToolsHermesWeb,
  chromeDevToolsJSCAndroid,
  chromeDevToolsJSCiOS,
  chromeDevToolsJSCWeb,
  chromeDevToolsV8Android,
  chromeDevToolsV8iOS,
  chromeDevToolsV8Web,
  flipperHermesAndroid,
  flipperHermesiOS,
  flipperHermesWeb,
  flipperJSCAndroid,
  flipperJSCiOS,
  flipperJSCWeb,
  flipperV8Android,
  flipperV8iOS,
  flipperV8Web,
} from './details';

export const detailsMap = new Map<string, string>([
  ['', ''],
  ['chromeDebugger/JSC/Android', chromeDebuggerJSCAndroid],
  ['chromeDebugger/JSC/iOS', chromeDebuggerJSCiOS],
  ['chromeDebugger/JSC/Web', chromeDebuggerJSCWeb],
  ['chromeDebugger/hermes/Android', chromeDebuggerHermesAndroid],
  ['chromeDebugger/hermes/iOS', chromeDebuggerHermesiOS],
  ['chromeDebugger/hermes/Web', chromeDebuggerHermesWeb],
  ['chromeDebugger/V8/Android', chromeDebuggerV8Android],
  ['chromeDebugger/V8/iOS', chromeDebuggerV8iOS],
  ['chromeDebugger/V8/Web', chromeDebuggerV8Web],
  ['chromeDevTools/JSC/Android', chromeDevToolsJSCAndroid],
  ['chromeDevTools/JSC/iOS', chromeDevToolsJSCiOS],
  ['chromeDevTools/JSC/Web', chromeDevToolsJSCWeb],
  ['chromeDevTools/hermes/Android', chromeDevToolsHermesAndroid],
  ['chromeDevTools/hermes/iOS', chromeDevToolsHermesiOS],
  ['chromeDevTools/hermes/Web', chromeDevToolsHermesWeb],
  ['chromeDevTools/V8/Android', chromeDevToolsV8Android],
  ['chromeDevTools/V8/iOS', chromeDevToolsV8iOS],
  ['chromeDevTools/V8/Web', chromeDevToolsV8Web],
  ['flipper/JSC/Android', flipperJSCAndroid],
  ['flipper/JSC/iOS', flipperJSCiOS],
  ['flipper/JSC/Web', flipperJSCWeb],
  ['flipper/hermes/Android', flipperHermesAndroid],
  ['flipper/hermes/iOS', flipperHermesiOS],
  ['flipper/hermes/Web', flipperHermesWeb],
  ['flipper/V8/Android', flipperV8Android],
  ['flipper/V8/iOS', flipperV8iOS],
  ['flipper/V8/Web', flipperV8Web],
  ['safariDevTools/JSC/Android', chromeDevToolsJSCAndroid],
  ['safariDevTools/JSC/iOS', chromeDevToolsJSCiOS],
  ['safariDevTools/JSC/Web', chromeDevToolsJSCWeb],
  ['safariDevTools/hermes/Android', chromeDevToolsJSCAndroid],
  ['safariDevTools/hermes/iOS', chromeDevToolsJSCiOS],
  ['safariDevTools/hermes/Web', chromeDevToolsJSCWeb],
  ['safariDevTools/V8/Android', chromeDevToolsJSCAndroid],
  ['safariDevTools/V8/iOS', chromeDevToolsJSCiOS],
  ['safariDevTools/V8/Web', chromeDevToolsJSCWeb],
  ['reactDevTools/JSC/Android', chromeDevToolsJSCAndroid],
  ['reactDevTools/JSC/iOS', chromeDevToolsJSCiOS],
  ['reactDevTools/JSC/Web', chromeDevToolsJSCWeb],
  ['reactDevTools/hermes/Android', chromeDevToolsJSCAndroid],
  ['reactDevTools/hermes/iOS', chromeDevToolsJSCiOS],
  ['reactDevTools/hermes/Web', chromeDevToolsJSCWeb],
  ['reactDevTools/V8/Android', chromeDevToolsJSCAndroid],
  ['reactDevTools/V8/iOS', chromeDevToolsJSCiOS],
  ['reactDevTools/V8/Web', chromeDevToolsJSCWeb],
]);
