import {
  ChromeDebuggerHermesAndroid,
  ChromeDebuggerHermesiOS,
  ChromeDebuggerJSCAndroid,
  ChromeDebuggerJSCiOS,
  ChromeDebuggerV8Android,
  ChromeDebuggerV8iOS,
  ChromeDevToolsHermesAndroid,
  ChromeDevToolsHermesiOS,
  ChromeDevToolsJSCAndroid,
  ChromeDevToolsJSCiOS,
  ChromeDevToolsV8Android,
  ChromeDevToolsV8iOS,
  FlipperHermesAndroid,
  FlipperHermesiOS,
  FlipperJSCAndroid,
  FlipperJSCiOS,
  FlipperV8Android,
  FlipperV8iOS,
  NothingSelected,
  ReactDevToolsHermesAndroid,
  ReactDevToolsHermesiOS,
  ReactDevToolsJSCAndroid,
  ReactDevToolsJSCiOS,
  ReactDevToolsV8Android,
  ReactDevToolsV8iOS,
  SafariDevToolsHermesAndroid,
  SafariDevToolsHermesiOS,
  SafariDevToolsJSCAndroid,
  SafariDevToolsJSCiOS,
  SafariDevToolsV8Android,
  SafariDevToolsV8iOS,
} from './details';

export const detailsMap = new Map<string, JSX.Element>([
  ['', NothingSelected()],
  ['Chrome Debugger/JSC/Android', ChromeDebuggerJSCAndroid()],
  ['Chrome Debugger/JSC/iOS', ChromeDebuggerJSCiOS()],
  ['Chrome Debugger/Hermes/Android', ChromeDebuggerHermesAndroid()],
  ['Chrome Debugger/Hermes/iOS', ChromeDebuggerHermesiOS()],
  ['Chrome Debugger/V8/Android', ChromeDebuggerV8Android()],
  ['Chrome Debugger/V8/iOS', ChromeDebuggerV8iOS()],
  ['Chrome DevTools/JSC/Android', ChromeDevToolsJSCAndroid()],
  ['Chrome DevTools/JSC/iOS', ChromeDevToolsJSCiOS()],
  ['Chrome DevTools/Hermes/Android', ChromeDevToolsHermesAndroid()],
  ['Chrome DevTools/Hermes/iOS', ChromeDevToolsHermesiOS()],
  ['Chrome DevTools/V8/Android', ChromeDevToolsV8Android()],
  ['Chrome DevTools/V8/iOS', ChromeDevToolsV8iOS()],
  ['Flipper/JSC/Android', FlipperJSCAndroid()],
  ['Flipper/JSC/iOS', FlipperJSCiOS()],
  ['Flipper/Hermes/Android', FlipperHermesAndroid()],
  ['Flipper/Hermes/iOS', FlipperHermesiOS()],
  ['Flipper/V8/Android', FlipperV8Android()],
  ['Flipper/V8/iOS', FlipperV8iOS()],
  ['Safari DevTools/JSC/Android', SafariDevToolsJSCAndroid()],
  ['Safari DevTools/JSC/iOS', SafariDevToolsJSCiOS()],
  ['Safari DevTools/Hermes/Android', SafariDevToolsHermesAndroid()],
  ['Safari DevTools/Hermes/iOS', SafariDevToolsHermesiOS()],
  ['Safari DevTools/V8/Android', SafariDevToolsV8Android()],
  ['Safari DevTools/V8/iOS', SafariDevToolsV8iOS()],
  ['React Developer Tools/JSC/Android', ReactDevToolsJSCAndroid()],
  ['React Developer Tools/JSC/iOS', ReactDevToolsJSCiOS()],
  ['React Developer Tools/Hermes/Android', ReactDevToolsHermesAndroid()],
  ['React Developer Tools/Hermes/iOS', ReactDevToolsHermesiOS()],
  ['React Developer Tools/V8/Android', ReactDevToolsV8Android()],
  ['React Developer Tools/V8/iOS', ReactDevToolsV8iOS()],
]);
