import {
  chromeDebuggerHermesAndroid,
  chromeDebuggerHermesiOS,
  chromeDebuggerJSCAndroid,
  chromeDebuggerJSCiOS,
  chromeDebuggerV8Android,
  chromeDebuggerV8iOS,
  chromeDevToolsHermesAndroid,
  chromeDevToolsHermesiOS,
  chromeDevToolsJSCAndroid,
  chromeDevToolsJSCiOS,
  chromeDevToolsV8Android,
  chromeDevToolsV8iOS,
  flipperHermesAndroid,
  flipperHermesiOS,
  flipperJSCAndroid,
  flipperJSCiOS,
  flipperV8Android,
  flipperV8iOS,
  nothingSelected,
  reactDevToolsHermesAndroid,
  reactDevToolsHermesiOS,
  reactDevToolsJSCAndroid,
  reactDevToolsJSCiOS,
  reactDevToolsV8Android,
  reactDevToolsV8iOS,
  safariDevToolsHermesAndroid,
  safariDevToolsHermesiOS,
  safariDevToolsJSCAndroid,
  safariDevToolsJSCiOS,
  safariDevToolsV8Android,
  safariDevToolsV8iOS,
} from './details';

export const detailsMap = new Map<string, JSX.Element>([
  ['', nothingSelected()],
  ['Chrome Debugger/JSC/Android', chromeDebuggerJSCAndroid()],
  ['Chrome Debugger/JSC/iOS', chromeDebuggerJSCiOS()],
  ['Chrome Debugger/hermes/Android', chromeDebuggerHermesAndroid()],
  ['Chrome Debugger/hermes/iOS', chromeDebuggerHermesiOS()],
  ['Chrome Debugger/V8/Android', chromeDebuggerV8Android()],
  ['Chrome Debugger/V8/iOS', chromeDebuggerV8iOS()],
  ['Chrome DevTools/JSC/Android', chromeDevToolsJSCAndroid()],
  ['Chrome DevTools/JSC/iOS', chromeDevToolsJSCiOS()],
  ['Chrome DevTools/hermes/Android', chromeDevToolsHermesAndroid()],
  ['Chrome DevTools/hermes/iOS', chromeDevToolsHermesiOS()],
  ['Chrome DevTools/V8/Android', chromeDevToolsV8Android()],
  ['Chrome DevTools/V8/iOS', chromeDevToolsV8iOS()],
  ['Flipper/JSC/Android', flipperJSCAndroid()],
  ['Flipper/JSC/iOS', flipperJSCiOS()],
  ['Flipper/hermes/Android', flipperHermesAndroid()],
  ['Flipper/hermes/iOS', flipperHermesiOS()],
  ['Flipper/V8/Android', flipperV8Android()],
  ['Flipper/V8/iOS', flipperV8iOS()],
  ['Safari DevTools/JSC/Android', safariDevToolsJSCAndroid()],
  ['Safari DevTools/JSC/iOS', safariDevToolsJSCiOS()],
  ['Safari DevTools/hermes/Android', safariDevToolsHermesAndroid()],
  ['Safari DevTools/hermes/iOS', safariDevToolsHermesiOS()],
  ['Safari DevTools/V8/Android', safariDevToolsV8Android()],
  ['Safari DevTools/V8/iOS', safariDevToolsV8iOS()],
  ['React DevTools/JSC/Android', reactDevToolsJSCAndroid()],
  ['React DevTools/JSC/iOS', reactDevToolsJSCiOS()],
  ['React DevTools/hermes/Android', reactDevToolsHermesAndroid()],
  ['React DevTools/hermes/iOS', reactDevToolsHermesiOS()],
  ['React DevTools/V8/Android', reactDevToolsV8Android()],
  ['React DevTools/V8/iOS', reactDevToolsV8iOS()],
]);
