import type { FontStyle, FontVariant } from '../types';

export const text: Record<FontVariant, FontStyle> = {
  body1: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 18,
  },
  body2: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 16,
  },
  body3: {
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 14,
  },
  heading1: {
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 40,
  },
  heading2: {
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 30,
  },
  heading3: {
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 26,
  },
  heading4: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 24,
  },
  label1: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 24,
  },
  label2: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
  },
  label3: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 16,
  },
  subHeading1: {
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 24,
  },
  subHeading2: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 22,
  },
  subHeading3: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
  },
};
