import type { FontStyle, FontVariant } from '../types';

const BASE_FONT = 'System';
const MONOSPACE_FONT = 'Menlo';

export const text: Record<FontVariant, FontStyle> = {
  body1: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 18,
    fontFamily: BASE_FONT,
  },
  body2: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 16,
    fontFamily: BASE_FONT,
  },
  body3: {
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 14,
    fontFamily: BASE_FONT,
  },
  heading1: {
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 40,
    fontFamily: BASE_FONT,
  },
  heading2: {
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 30,
    fontFamily: BASE_FONT,
  },
  heading3: {
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 26,
    fontFamily: BASE_FONT,
  },
  heading4: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 24,
    fontFamily: BASE_FONT,
  },
  label1: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 24,
    fontFamily: BASE_FONT,
  },
  label2: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
    fontFamily: BASE_FONT,
  },
  label3: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 16,
    fontFamily: BASE_FONT,
  },
  subHeading1: {
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 24,
    fontFamily: BASE_FONT,
  },
  subHeading2: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 22,
    fontFamily: BASE_FONT,
  },
  subHeading3: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
    fontFamily: BASE_FONT,
  },
  code: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0.25,
    lineHeight: 10,
    fontFamily: MONOSPACE_FONT,
  },
};
