name: Cache DerivedData
description: Cache Xcode DerivedData for faster builds

inputs:
  platform:
    description: The platform (ios, macos, tvos)
    required: true
  working-directory:
    description: The app directory (e.g., apps/fabric-example)
    required: true

runs:
  using: 'composite'
  steps:
    - name: Restore DerivedData cache
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: derived-${{ inputs.platform }}-${{ hashFiles(
          format('{0}/Podfile', inputs['working-directory']),
          format('{0}/Podfile.lock', inputs['working-directory']),
          format('{0}/**/*.xcworkspace/**', inputs['working-directory']),
          format('{0}/**/*.xcodeproj/**', inputs['working-directory']))}}
