require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

config = use_native_modules!
use_react_native!(:path => config["reactNativePath"])

def pods()
  pod 'RNReanimated', :path => '../../'
  pod 'ReactCommon/turbomodule/samples', :path => '../node_modules/react-native/ReactCommon'

  # Additional Pods which aren't included in the default Podfile
  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  use_native_modules!
end

target 'ReanimatedExample' do
  project 'ReanimatedExample'
  pods()
end

target 'ReanimatedExampleTests' do
  inherit! :complete
  pods()
end
