name: Android validation
description: Lint Android Java/Kotlin code and C++ code

inputs:
  package-dir:
    description: The package directory (e.g., packages/react-native-reanimated)
    required: true
  build-package:
    description: Whether to build the package before linting
    default: 'true'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'

    - name: Set up C++ lint tools
      uses: ./.github/actions/setup-cpp-lint
      with:
        install-cmakelang: 'true'

    - name: Clear annotations
      shell: bash
      run: .github/workflows/helper/clear-annotations.sh

    - name: Install monorepo node dependencies
      shell: bash
      run: yarn install --immutable

    - name: Build package
      if: ${{ inputs.build-package == 'true' }}
      shell: bash
      working-directory: ${{ inputs.package-dir }}
      run: yarn build

    - name: Lint Android
      shell: bash
      working-directory: ${{ inputs.package-dir }}
      run: yarn lint:android
