import type { FontStyle, FontVariant } from '@/types';

const BASE_FONT = 'Poppins';
const MONOSPACE_FONT = 'UbuntuMono';

export const text: Record<FontVariant, FontStyle> = {
  body1: {
    fontFamily: `${BASE_FONT}-Regular`,
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 18,
  },
  body2: {
    fontFamily: `${BASE_FONT}-Light`,
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: '300',
    letterSpacing: 0,
    lineHeight: 16,
  },
  body3: {
    fontFamily: `${BASE_FONT}-Thin`,
    fontSize: 10,
    fontStyle: 'normal',
    fontWeight: '100',
    letterSpacing: 0,
    lineHeight: 14,
  },
  code: {
    fontFamily: `${MONOSPACE_FONT}-Regular`,
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 16,
  },
  heading1: {
    fontFamily: `${BASE_FONT}-Bold`,
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 40,
  },
  heading2: {
    fontFamily: `${BASE_FONT}-Bold`,
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 30,
  },
  heading3: {
    fontFamily: `${BASE_FONT}-SemiBold`,
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 26,
  },
  heading4: {
    fontFamily: `${BASE_FONT}-SemiBold`,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 24,
  },
  inlineCode: {
    fontFamily: `${MONOSPACE_FONT}-Regular`,
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: 0.4,
    lineHeight: 20,
  },
  label1: {
    fontFamily: `${BASE_FONT}-SemiBold`,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 24,
  },
  label2: {
    fontFamily: `${BASE_FONT}-SemiBold`,
    fontSize: 13,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 20,
  },
  label3: {
    fontFamily: `${BASE_FONT}-SemiBold`,
    fontSize: 11,
    fontStyle: 'normal',
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 16,
  },
  subHeading1: {
    fontFamily: `${BASE_FONT}-Medium`,
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 24,
  },
  subHeading2: {
    fontFamily: `${BASE_FONT}-Medium`,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 22,
  },
  subHeading3: {
    fontFamily: `${BASE_FONT}-Medium`,
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 18,
  },
};
