
/**
 * This code was generated by
 * [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorsH.js
 */

#pragma once

#include <react/renderer/components/rnreanimated/ShadowNodes.h>
#include <react/renderer/core/ConcreteComponentDescriptor.h>

#include "RNReanimatedSharedTransitionBoundaryComponentDescriptor.h"

namespace facebook::react {} // namespace facebook::react
