
/**
 * This code was generated by
 * [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>

#include "RNReanimatedSharedTransitionBoundaryShadowNode.h"

namespace facebook::react {

class RNReanimatedSharedTransitionBoundaryComponentDescriptor final
    : public ConcreteComponentDescriptor<RNReanimatedSharedTransitionBoundaryShadowNode> {
  using ConcreteComponentDescriptor::ConcreteComponentDescriptor;
  void adopt(ShadowNode &shadowNode) const override {
    react_native_assert(dynamic_cast<RNReanimatedSharedTransitionBoundaryShadowNode *>(&shadowNode));

    ConcreteComponentDescriptor::adopt(shadowNode);
  }
};

} // namespace facebook::react
