/**
 * This code was generated by
 * [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generated by codegen project: GenerateStateH.js
 */
#pragma once

#ifdef ANDROID
#include <folly/dynamic.h>
#endif

namespace facebook::react {

class RNReanimatedSharedTransitionBoundaryState {
 public:
  RNReanimatedSharedTransitionBoundaryState() = default;

#ifdef ANDROID
  RNReanimatedSharedTransitionBoundaryState(
      RNReanimatedSharedTransitionBoundaryState const &previousState,
      folly::dynamic data) {};
  folly::dynamic getDynamic() const {
    return {};
  };
#endif
};

} // namespace facebook::react
