name: 'Read Compatibility JSON'
description: 'Reads compatibility.json file and outputs platforms and react-native-versions with nightly version added'
runs:
  using: 'composite'
  steps:
    - name: Read compatibility.json with nightly
      id: read-compatibility-json
      working-directory: packages/react-native-reanimated
      shell: bash
      run: |
        PLATFORMS=$(node -e "console.log(JSON.stringify(JSON.parse(require('fs').readFileSync('compatibility.json', 'utf8'))['platforms']))")
        VERSIONS=$(node -e "console.log(JSON.stringify(JSON.parse(require('fs').readFileSync('compatibility.json', 'utf8'))['react-native-versions']))")
        VERSIONS_WITH_NIGHTLY=$(node -e "const versions = JSON.parse(require('fs').readFileSync('compatibility.json', 'utf8'))['react-native-versions']; versions.push('nightly'); console.log(JSON.stringify(versions))")
        echo "platforms=$PLATFORMS" >> /tmp/platforms.json
        echo "react-native-versions=$VERSIONS" >> /tmp/react-native-versions.json
        echo "react-native-versions-with-nightly=$VERSIONS_WITH_NIGHTLY" >> /tmp/react-native-versions-with-nightly.json
