name: 'Reanimated Compatibility Check - Build'
description: 'Check React Native Reanimated compatibility with different React Native versions'
inputs:
  react-native-versions:
    description: 'JSON array of React Native versions to test'
    required: true
  platform:
    description: 'Platform to test (iOS or Android)'
    required: true
  mode:
    description: 'Build mode (Debug or Release)'
    required: true
  github-sha:
    description: 'GitHub SHA to use for installing packages'
    required: true
  app-name:
    description: 'Name of the test app'
    default: 'app'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Yarn
      if: ${{ steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      run: corepack enable && yarn init

    - name: Install React Native CLI
      if: ${{ steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      run: yarn add @react-native-community/cli

    - name: Create app
      if: ${{ steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      run: yarn rnc-cli init ${{ inputs.app-name }} --version ${{ inputs.react-native-versions }} --skip-install --install-pods 0 --skip-git-init

    - name: Setup Yarn Modern in app
      if: ${{ steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      working-directory: ${{ inputs.app-name }}
      run: |
        touch yarn.lock
        yarn set version berry
        yarn config set nodeLinker node-modules

    - name: Install Worklets
      if: ${{ steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      working-directory: ${{ inputs.app-name }}
      run: yarn add "react-native-worklets@https://github.com/software-mansion/react-native-reanimated.git#workspace=react-native-worklets&commit=${{ inputs.github-sha }}"

    - name: Install Reanimated
      if: ${{ steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      working-directory: ${{ inputs.app-name }}
      run: yarn add "react-native-reanimated@https://github.com/software-mansion/react-native-reanimated.git#workspace=react-native-worklets&commit=${{ inputs.github-sha }}"

    - name: Select Xcode (iOS)
      if: ${{ inputs.platform == 'iOS' && steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      run: sudo xcode-select --switch /Applications/Xcode_16.4.app

    - name: Install Pods
      if: ${{ inputs.platform == 'iOS' && steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      working-directory: ${{ inputs.app-name }}/ios
      run: bundle install && bundle exec pod update

    - name: Build app (iOS)
      if: ${{ inputs.platform == 'iOS' && steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      working-directory: ${{ inputs.app-name }}/ios
      run: xcodebuild -workspace ${{ inputs.app-name }}.xcworkspace -configuration ${{ inputs.mode }} -scheme ${{ inputs.app-name }} -destination "generic/platform=iOS Simulator" -quiet

    - name: Build app (Android)
      if: ${{ inputs.platform == 'Android' && steps.check-react-native-version.outputs.SKIP_BUILD != 'true' }}
      shell: bash
      working-directory: ${{ inputs.app-name }}/android
      run: ./gradlew assemble${{ inputs.mode }} --console=plain
