name: Babel plugin static check
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - '.github/workflows/babel-plugin-static-check.yml'
      - 'packages/react-native-worklets/plugin/**'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/babel-plugin-static-check.yml'
      - 'packages/react-native-worklets/plugin/**'
  workflow_call:
  workflow_dispatch:

jobs:
  babel-plugin-static-check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            bundle_output: /dev/null
          - os: windows-latest
            bundle_output: 'NUL'
    runs-on: ${{ matrix.os }}
    concurrency:
      group: babel-plugin-static-check-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      EXAMPLE_DIR: apps/fabric-example
      WORKLETS_DIR: packages/react-native-worklets
      PLUGIN_DIR: packages/react-native-worklets/plugin
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          cache: 'yarn'
      - name: Clear annotations
        shell: bash
        run: .github/workflows/helper/clear-annotations.sh

      - name: Install monorepo dependencies
        run: yarn install --immutable
      - name: Build Worklets
        if: matrix.os != 'windows-latest'
        working-directory: ${{ env.WORKLETS_DIR }}
        run: yarn build

      - name: Diff
        id: diff
        if: matrix.os != 'windows-latest'
        run: git update-index --refresh && git diff-index --quiet HEAD --
      - name: Show diff
        if: failure() && steps.diff.outcome == 'failure'
        run: git diff
      - name: Check types
        if: matrix.os != 'windows-latest'
        working-directory: ${{ env.PLUGIN_DIR }}
        run: yarn type:check
      - name: Lint and format
        if: matrix.os != 'windows-latest'
        working-directory: ${{ env.PLUGIN_DIR }}
        run: yarn lint

      - name: Unit tests
        working-directory: ${{ env.WORKLETS_DIR }}
        run: yarn jest plugin
      - name: Check Example App bundling
        shell: bash
        working-directory: ${{ env.EXAMPLE_DIR }}
        run:
          yarn react-native bundle --reset-cache --entry-file='App.tsx' --bundle-output='${{ matrix.bundle_output }}'
          --dev=true --platform=android

      - name: Disable Bundle Mode
        shell: bash
        run: yarn toggle-bundle-mode
      - name: Check Example App bundling (Eval Mode)
        shell: bash
        working-directory: ${{ env.EXAMPLE_DIR }}
        run:
          yarn react-native bundle --reset-cache --entry-file='App.tsx' --bundle-output='${{ matrix.bundle_output }}'
          --dev=true --platform=android
