name: Build/test NextExample
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - .github/workflows/build-next-example.yml
      - 'packages/react-native-reanimated/src/**'
      - 'packages/react-native-reanimated/NextExample/**'
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: build-next-example-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Install monorepo node dependencies
        run: yarn install --immutable
      - name: Install Reanimated node dependencies
        working-directory: packages/react-native-reanimated
        run: yarn install --immutable
      - name: Build Reanimated package
        working-directory: packages/react-native-reanimated
        run: yarn build

      - name: Install NextExample node_modules
        working-directory: apps/next-example
        run: yarn install --immutable

      - name: Compile production build
        working-directory: apps/next-example
        run: yarn build:next

      - name: Run e2e tests
        working-directory: apps/next-example
        run: yarn e2e:headless
