name: Test build in monorepo
on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      os:
        required: true
        type: string
      concurrency_group:
        required: true
        type: string
      is_hoisted:
        required: true
        type: boolean

jobs:
  build:
    name: Build monorepo with Reanimated
    runs-on: ${{ inputs.runs_on }}
    concurrency:
      group: ${{ inputs.concurrency_group }}
      cancel-in-progress: true
    steps:
      - name: Create monorepo
        run: |
          mkdir monorepo
          cd monorepo
          echo '{"name":"rnos-monorepo-tester","version":"1.0.0","license":"MIT","private":true,"workspaces":{"packages":["RootApp","packages/PackageApp"],"nohoist":["**/react","**/react-dom","**/react-native","**/react-native/**","**/react-native-codegen","**/react-native-dev-menu"]}}' > package.json
          yarn
          mkdir packages
      - name: Create PackageApp
        # working-directory: monorepo/packages
        run: |
          pwd
          ls -la
          cd monorepo/packages
          pwd
          ls -la
          npx
          npx -h
          npx react-native init PackageApp
      - name: Create RootApp
        # working-directory: monorepo
        run: |
          pwd
          ls -la
          cd monorepo
          pwd
          ls -la
          npx
          npx -h
          npx react-native init RootApp
      
      - name: Install dependencies for RootApp
        working-directory: monorepo/RootApp
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install dependencies for packages/PackageApp
        working-directory: monorepo/packages/PackageApp
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      
      - name: Setup hoisted Reanimated
        if: ${{ runner.is_hoisted }}
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }} -W

      - name: Install Pods for RootApp
        if: ${{ runner.os == 'iOS' }}
        working-directory: monorepo/RootApp/ios
        run: pod install
      - name: Install Pods for PackageApp
        if: ${{ runner.os == 'iOS' }}
        working-directory: monorepo/packages/PackageApp/ios
        run: pod install

      - name: Build app RootApp
        if: ${{ runner.os == 'iOS' }}
        working-directory: monorepo/RootApp
        run: npx react-native run-ios
      - name: Build app PackageApp
        if: ${{ runner.os == 'iOS' }}
        working-directory: monorepo/packages/PackageApp
        run: npx react-native run-ios

      - name: Build Android RootApp
        if: ${{ runner.os == 'Android' }}
        working-directory: monorepo/RootApp/android
        run: ./gradlew assembleDebug --console=plain
      - name: Build Android PackageApp
        if: ${{ runner.os == 'Android' }}
        working-directory: monorepo/packages/PackageApp/android
        run: ./gradlew assembleDebug --console=plain
