name: Test monorepo build
on:
  pull_request:
    paths:
      - .github/workflows/build-monorepo.yml
      - .github/workflows/build-monorepo-action.yml
      - RNReanimated.podspec
      - scripts/reanimated_utils.rb
      - android/build.gradle
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-monorepo.yml
      - .github/workflows/build-monorepo-action.yml
      - RNReanimated.podspec
      - scripts/reanimated_utils.rb
      - android/build.gradle
  workflow_call:

jobs:
  build_android_reanimated_non_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: Android (non-hoisted Reanimated)
    uses: ./.github/workflows/build-monorepo-action.yml
    with:
      platform: Android
      concurrency_group: build_monorepo_android_in_app_reanimated-${{ github.ref }}
      is_hoisted: false

  build_ios_reanimated_non_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: iOS (non-hoisted Reanimated)
    uses: ./.github/workflows/build-monorepo-action.yml
    with:
      platform: iOS
      concurrency_group: build_monorepo_ios_in_app_reanimated-${{ github.ref }}
      is_hoisted: false

  build_android_reanimated_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: Android (hoisted Reanimated)
    uses: ./.github/workflows/build-monorepo-action.yml
    with:
      platform: Android
      concurrency_group: build_monorepo_android_reanimated_hoisted-${{ github.ref }}
      is_hoisted: true

  build_ios_reanimated_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: iOS (hoisted Reanimated)
    uses: ./.github/workflows/build-monorepo-action.yml
    with:
      platform: iOS
      concurrency_group: build_monorepo_ios_reanimated_hoisted-${{ github.ref }}
      is_hoisted: true
