name: Test build in monorepo
on:
  pull_request:
    paths:
      - .github/workflows/build-monorepo.yml
      - RNReanimated.podspec
      - android/build.gradle
  push:
    branches:
      - main

jobs:
  build_android_reanimated_in_app:
    name: Build Android with in app Reanimated
    uses: ./.github/workflows/build-monorepo.yml
    with:
      runs_on: ubuntu-latest
      os: Android
      concurrency_group: build_monorepo_android_in_app_reanimated
      is_hoisted: false

  # build_ios_reanimated_in_app:
  #   name: Build iOS with in app Reanimated
  #   uses: ./.github/workflows/build-monorepo.yml
  #   with:
  #     runs_on: macos-12
  #     os: iOS
  #     concurrency_group: build_monorepo_ios_in_app_reanimated
  #     is_hoisted: false

  # build_android_reanimated_hoisted:
  #   name: Build Android with hoisted Reanimated
  #   uses: ./.github/workflows/build-monorepo.yml
  #   with:
  #     runs_on: ubuntu-latest
  #     os: Android
  #     concurrency_group: build_monorepo_android_reanimated_hoisted
  #     is_hoisted: true

  # build_ios_reanimated_hoisted:
  #   name: Build iOS with hoisted Reanimated
  #   uses: ./.github/workflows/build-monorepo.yml
  #   with:
  #     runs_on: macos-12
  #     os: iOS
  #     concurrency_group: build_monorepo_ios_reanimated_hoisted
  #     is_hoisted: true
