name: Test build in monorepo
on:
  pull_request:
    paths:
      - .github/workflows/build-monorepo.yml
      - RNReanimated.podspec
      - android/build.gradle
  push:
    branches:
      - main

jobs:
  build_android_reanimated_in_app:
    runs-on: ubuntu-latest
    concurrency:
      group: build_monorepo_android_reanimated_in_app
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: 'software-mansion-labs/rnos-monorepo-tester'
          path: 'monorepo'
      - name: Install dependencies for ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install dependencies for package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Build ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA/android
        run: ./gradlew assembleDebug --console=plain
      - name: Build package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA/android
        run: ./gradlew assembleDebug --console=plain

  build_ios_reanimated_in_app:
    runs-on: macos-12
    concurrency:
      group: build_monorepo_ios_reanimated_in_app
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: 'software-mansion-labs/rnos-monorepo-tester'
          path: 'monorepo'
      - name: Install dependencies for ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install dependencies for package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install Pods for ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA/ios
        run: pod install
      - name: Install Pods for package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA/ios
        run: pod install
      - name: Build app ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA
        run: npx react-native run-ios
      - name: Build app package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA
        run: npx react-native run-ios

  build_android_reanimated_hoisted:
    runs-on: ubuntu-latest
    concurrency:
      group: build_monorepo_android_reanimated_hoisted
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: 'software-mansion-labs/rnos-monorepo-tester'
          path: 'monorepo'
      - name: Install dependencies for ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install dependencies for package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install Reanimated in workspace
        working-directory: monorepo
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }} -W
      - name: Build ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA/android
        run: ./gradlew assembleDebug --console=plain
      - name: Build package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA/android
        run: ./gradlew assembleDebug --console=plain

  build_ios_reanimated_hoisted:
    runs-on: macos-12
    strategy:
      matrix:
        working-directory: [Example]
      fail-fast: false
    concurrency:
      group: build_monorepo_ios_reanimated_hoisted
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: 'software-mansion-labs/rnos-monorepo-tester'
          path: 'monorepo'
      - name: Install dependencies for ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install dependencies for package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }}
      - name: Install Reanimated in workspace
        working-directory: monorepo
        run: yarn add github:software-mansion/react-native-reanimated#${{ github.ref }} -W
      - name: Install Pods for ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA/ios
        run: pod install
      - name: Install Pods for package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA/ios
        run: pod install
      - name: Build app ReactNativeRootA
        working-directory: monorepo/ReactNativeRootA
        run: npx react-native run-ios
      - name: Build app package/ReactNativeA
        working-directory: monorepo/package/ReactNativeA
        run: npx react-native run-ios
