name: Build release npm package, Reanimated 3

on:
  workflow_dispatch:

jobs:
  call-build-workflow-rea-v3:
    if: github.repository == 'software-mansion/react-native-reanimated'
    uses: ./.github/workflows/build-npm-package-action.yml
    with:
      version: release
