name: Check Expo dev-client nightly build
env:
  YARN_ENABLE_HARDENED_MODE: 0
  SCRIPT_PATH: ${{github.workspace}}/reanimated_repo/.github/workflows/helper/configureDevClient.js
on:
  pull_request:
    paths:
      - .github/workflows/check-expo-dev-client-nightly.yml
  schedule:
    - cron: '0 0 * * *' # after publishing new nightly version on NPM
  workflow_dispatch:

jobs:
  build_ios:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: macos-14
    strategy:
      matrix:
        react-native-architecture: ['Paper', 'Fabric']
      fail-fast: false
    concurrency:
      group: ios-expo-dev-client-${{ matrix.react-native-architecture }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out reanimated repository
        uses: actions/checkout@v4
        with:
          path: 'reanimated_repo'
      - name: Create Expo app
        run: npx create-expo-app ExpoApp
      - name: Install expo-dev-client
        working-directory: ExpoApp
        run: |
          if npm view expo dist-tags | grep -q 'next:' ; then 
            npm install expo@next
          else 
            npm install expo@latest
          fi
      - name: Setup configuration
        working-directory: ExpoApp
        run: node ${{ env.SCRIPT_PATH }} setBundleIdentifier
      - name: Expo prebuild
        working-directory: ExpoApp
        run: npx expo prebuild
      - name: Install Reanimated
        working-directory: ExpoApp
        run: npm install react-native-reanimated@nightly
      - name: Set Fabric
        working-directory: ExpoApp
        if: ${{ matrix.react-native-architecture == 'Fabric' }}
        run: node ${{ env.SCRIPT_PATH }} setupFabricIOS
      - name: Install Pods
        working-directory: ExpoApp/ios
        run: pod install
      - name: Build app
        working-directory: ExpoApp
        run: npx react-native run-ios --simulator='iPhone 14' --terminal='Terminal'

  build_android:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react-native-architecture: ['Paper', 'Fabric']
      fail-fast: false
    concurrency:
      group: android-expo-dev-client-${{ matrix.react-native-architecture }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out reanimated repository
        uses: actions/checkout@v4
        with:
          path: 'reanimated_repo'
      - name: Create Expo app
        run: npx create-expo-app ExpoApp
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Install expo-dev-client
        working-directory: ExpoApp
        run: |
          if npm view expo dist-tags | grep -q 'next:' ; then 
            npm install expo@next
          else 
            npm install expo@latest
          fi
      - name: Setup configuration
        working-directory: ExpoApp
        run: node ${{ env.SCRIPT_PATH }} setBundleIdentifier
      - name: Expo prebuild
        working-directory: ExpoApp
        run: npx expo prebuild
      - name: Install Reanimated
        working-directory: ExpoApp
        run: npm install react-native-reanimated@nightly
      - name: Set Fabric
        working-directory: ExpoApp
        if: ${{ matrix.react-native-architecture == 'Fabric' }}
        run: node ${{ env.SCRIPT_PATH }} setupFabricAndroid
      - name: Build app
        working-directory: ExpoApp/android
        run: ./gradlew assembleDebug --console=plain
