name: Validate urls in source code
on:
  pull_request:
    paths:
      - .github/workflows/detect-broken-urls-nightly.yml
      - scripts/detect-broken-urls.js
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  run:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn add node-fetch@2
      - name: Validate urls
        run: node scripts/validate-urls.js
