name: Docs Reanimated build check
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - '.github/workflows/docs-reanimated-build-check.yml'
      - docs/docs-reanimated/**
      - packages/react-native-reanimated/compatibility.json
  merge_group:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  docs-reanimated-build-check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    env:
      REANIMATED_DOCS_DIR: docs/docs-reanimated
      WORKLETS_DOCS_DIR: docs/docs-worklets
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh
      - name: Install monorepo node dependencies
        working-directory: packages/react-native-reanimated
        run: yarn install
      - name: Lint check Reanimated docs
        working-directory: ${{ env.REANIMATED_DOCS_DIR }}
        run: yarn lint
      - name: Build Reanimated docs
        working-directory: ${{ env.REANIMATED_DOCS_DIR }}
        run: yarn build
      - name: Lint check Worklets docs
        working-directory: ${{ env.WORKLETS_DOCS_DIR }}
        run: yarn lint
      - name: Build Worklets docs
        working-directory: ${{ env.WORKLETS_DOCS_DIR }}
        run: yarn build
