name: GitHub Pull Request description format
on:
  pull_request:
    types:
      - opened

jobs:
  github-pull-request-description-format:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        uses: software-mansion-labs/pr-description@main
        with:
          content: ''
          regex: "<!-- .* -->\n"
          regexFlags: img
          token: ${{ secrets.GITHUB_TOKEN }}
