name: GitHub Pull Request label format
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  github-pull-request-label-format:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Label PR
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          configuration-path: '.github/labeler.yml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
