name: Test monorepo build
on:
  pull_request:
    paths:
      - .github/workflows/monorepo-check.yml
      - android/build.gradle
      - android/CMakeList.txt
      - RNReanimated.podspec
  push:
    branches:
      - main

jobs:
  prepare_monorepo_v1:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: monorepo
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: mmazzarolo/react-native-universal-monorepo
          path: monorepo
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Add reanimated to workspace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn add react-native-reanimated -W
      - name: Add reanimated to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add react-native-reanimated
      - name: Add reanimated to `web` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/web
        run: yarn add react-native-reanimated
      - name: Pod install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios:pods

  build_android_v1:
    needs: prepare_monorepo_v1
    runs-on: ubuntu-latest
    concurrency:
      group: monorepo-android-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: A
        run: ls

  build_ios_v1:
    needs: prepare_monorepo_v1
    runs-on: macos-12
    concurrency:
      group: monorepo-ios-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: A
        run: ls

  prepare_monorepo_v2:
    needs: [build_android_v1, build_ios_v1]
    runs-on: ubuntu-latest
    steps:
      - name: Remove reanimated from workspace
        run: cd monorepo && yarn remove react-native-reanimated -W
      - name: Pod install
        run: cd monorepo && yarn ios:pods

  build_android_v2:
    needs: prepare_monorepo_v2
    runs-on: ubuntu-latest
    concurrency:
      group: monorepo-android-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: A
        run: ls

  build_ios_v2:
    needs: prepare_monorepo_v2
    runs-on: macos-12
    concurrency:
      group: monorepo-ios-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: A
        run: ls