name: Test monorepo build
on:
  pull_request:
    paths:
      - .github/workflows/monorepo-check.yml
      - android/build.gradle
      - android/CMakeList.txt
      - RNReanimated.podspec
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: monorepo
  REANIMATED_VERSION: github:software-mansion/react-native-reanimated#${{ github.sha }}
  REACT_NATIVE_VERSION: react-native@0.68.4

jobs:
  build_android_v1:
    name: Monorepo with hoisted Reanimated (Android)
    runs-on: ubuntu-latest
    concurrency:
      group: monorepo-android_v1-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: mmazzarolo/react-native-universal-monorepo
          path: monorepo
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Add Reanimated to workspace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn add ${{ env.REANIMATED_VERSION }} -W
      - name: Set ReactNative version in `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REACT_NATIVE_VERSION }}
      - name: Add Reanimated to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Add reanimated to `web` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/web
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn android:start

  build_ios_v1:
    name: Monorepo with hoisted Reanimated (iOS)
    runs-on: macos-12
    concurrency:
      group: monorepo-ios_v1-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: mmazzarolo/react-native-universal-monorepo
          path: monorepo
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Add Reanimated to workspace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn add ${{ env.REANIMATED_VERSION }} -W
      - name: Set ReactNative version in `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REACT_NATIVE_VERSION }}
      - name: Add Reanimated to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Add reanimated to `web` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/web
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Pod install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios:pods
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios:start

  build_android_v2:
    name: Monorepo with hoisted ReactNative (Android)
    runs-on: ubuntu-latest
    concurrency:
      group: monorepo-android_v2-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: mmazzarolo/react-native-universal-monorepo
          path: monorepo
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Add ReactNative to workspace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn add ${{ env.REACT_NATIVE_VERSION }} -W
      - name: Set ReactNative version in `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REACT_NATIVE_VERSION }}
      - name: Add ReactNative to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REACT_NATIVE_VERSION }}
      - name: Add Reanimated to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Add reanimated to `web` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/web
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn android:start

  build_ios_v2:
    name: Monorepo with hoisted ReactNative (iOS)
    runs-on: macos-12
    concurrency:
      group: monorepo-ios_v2-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: mmazzarolo/react-native-universal-monorepo
          path: monorepo
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Add ReactNative to workspace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn add ${{ env.REACT_NATIVE_VERSION }} -W
      - name: Set ReactNative version in `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REACT_NATIVE_VERSION }}
      - name: Add ReactNative to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REACT_NATIVE_VERSION }}
      - name: Add Reanimated to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Add reanimated to `web` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/web
        run: yarn add ${{ env.REANIMATED_VERSION }}
      - name: Pod install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios:pods
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios:start
