name: Monorepo app Reanimated build check [Nightly]
on:
  pull_request:
    paths:
      - .github/workflows/monorepo-app-reanimated-build-check-nightly.yml
      - .github/workflows/monorepo-app-reanimated-build-check-action.yml
      - RNReanimated.podspec
      - packages/react-native-reanimated/scripts/reanimated_utils.rb
      - packages/react-native-reanimated/android/build.gradle
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/monorepo-app-reanimated-build-check-nightly.yml
      - .github/workflows/monorepo-app-reanimated-build-check-action.yml
      - packages/react-native-reanimated/RNReanimated.podspec
      - packages/react-native-reanimated/scripts/reanimated_utils.rb
      - packages/react-native-reanimated/android/build.gradle
  schedule:
    - cron: '37 19 * * *' # at 21:37 every day
  workflow_call:
  workflow_dispatch:

jobs:
  build_android_reanimated_non_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: Android (non-hoisted Reanimated)
    uses: ./.github/workflows/monorepo-app-reanimated-build-check-action.yml
    with:
      platform: Android
      concurrency_group: build_monorepo_android_in_app_reanimated-${{ github.ref }}
      is_hoisted: false

  build_ios_reanimated_non_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: iOS (non-hoisted Reanimated)
    uses: ./.github/workflows/monorepo-app-reanimated-build-check-action.yml
    with:
      platform: iOS
      concurrency_group: build_monorepo_ios_in_app_reanimated-${{ github.ref }}
      is_hoisted: false

  build_android_reanimated_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: Android (hoisted Reanimated)
    uses: ./.github/workflows/monorepo-app-reanimated-build-check-action.yml
    with:
      platform: Android
      concurrency_group: build_monorepo_android_reanimated_hoisted-${{ github.ref }}
      is_hoisted: true

  build_ios_reanimated_hoisted:
    if: github.repository == 'software-mansion/react-native-reanimated'
    name: iOS (hoisted Reanimated)
    uses: ./.github/workflows/monorepo-app-reanimated-build-check-action.yml
    with:
      platform: iOS
      concurrency_group: build_monorepo_ios_reanimated_hoisted-${{ github.ref }}
      is_hoisted: true
