name: Test monorepo build
on:
  pull_request:
    paths:
      - .github/workflows/monorepo-check.yml
      - android/build.gradle
      - android/CMakeList.txt
      - RNReanimated.podspec
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: monorepo
  REANIMATED_CURRENT_VERSION: github:software-mansion/react-native-reanimated#${{ github.sha }}

jobs:
  build_android_v1:
    runs-on: ubuntu-latest
    concurrency:
      group: monorepo-android-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: mmazzarolo/react-native-universal-monorepo
          path: monorepo
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Add Reanimated to workspace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn add ${{ env.REANIMATED_CURRENT_VERSION }} -W
      - name: Add Reanimated to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REANIMATED_CURRENT_VERSION }}
      - name: Add reanimated to `web` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/web
        run: yarn add ${{ env.REANIMATED_CURRENT_VERSION }}
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn android:start

  build_ios_v1:
    runs-on: macos-12
    concurrency:
      group: monorepo-ios-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Clone monorepo
        uses: actions/checkout@v3
        with:
          repository: mmazzarolo/react-native-universal-monorepo
          path: monorepo
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Add Reanimated to workspace
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn add ${{ env.REANIMATED_CURRENT_VERSION }} -W
      - name: Add Reanimated to `mobile` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/mobile
        run: yarn add ${{ env.REANIMATED_CURRENT_VERSION }}
      - name: Add reanimated to `web` app
        working-directory: ${{ env.WORKING_DIRECTORY }}/packages/web
        run: yarn add ${{ env.REANIMATED_CURRENT_VERSION }}
      - name: Pod install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios:pods
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios:start
