name: NPM Reanimated publish
on:
  # temporary
  push:
  merge_group:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Whether to publish the package or just do a dry run.'
        required: false
        type: boolean
        default: false
      version:
        description: 'Version to be published if cannot be inferred automatically, use for stable releases.'
        required: false
        type: string
        default: ''

      release-type:
        description: 'Release type to be published (stable, nightly, beta, rc)'
        type: choice
        options:
          - stable
          - nightly
          - beta
          - rc
        required: true

      npm-tag:
        description: 'NPM tag to publish under (usually inferred from release type and version)'
        required: false
        type: string
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 22

      - name: Build and publish
        uses: software-mansion/npm-package-publish@5a4fbd99427adb6ab4fe3557a9a6044c22e8f319
        with:
          release-type: ${{ github.event.inputs.release-type || 'nightly' }}
          version: ${{ github.event.inputs.version }}
          npm-tag: ${{ github.event.inputs.npm-tag }}
          dry-run: ${{ !github.event.inputs.publish }}
          package-name: 'react-native-reanimated'
          package-json-path: 'packages/react-native-reanimated/package.json'
          version-getter-script: 'scripts/resolve-release-version.js'
          perform-git-operations: 'false'
