name: NPM Worklets publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Publish to npm
        uses: ./.github/actions/npm-package-publish
        with:
          package-name: 'react-native-worklets'
          package-json-path: 'packages/react-native-worklets/package.json'
          release-type: 'nightly'
          perform-git-operations: 'false'
          dry-run: 'true'
