name: npm reanimated publish
permissions:
  contents: read
  id-token: write
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/npm-reanimated-publish.yml'
      - '.github/workflows/npm-package-publish.yml'
      - '.github/actions/npm-package-publish/**'
  pull_request:
    paths:
      - '.github/workflows/npm-reanimated-publish.yml'
      - '.github/workflows/npm-package-publish.yml'
      - '.github/actions/npm-package-publish/**'
  merge_group:
    branches:
      - main
  workflow_dispatch:
    inputs:
      publish:
        description: 'Do you want to publish the package? Leave it unchecked to do a dry run without publishing.'
        required: false
        type: boolean
        default: false

      release-type:
        description: 'Release type'
        type: choice
        options:
          - stable
          - nightly
          - beta
          - rc
        required: true

      version:
        description: 'Version to be published (only for stable releases)'
        required: false
        type: string
        default: ''

      npm-tag:
        description: 'npm tag to publish under (only if different than release type)'
        required: false
        type: string
        default: ''
  schedule:
    - cron: '27 23 * * *' # at 23:27 every day

jobs:
  npm-reanimated-publish:
    uses: ./.github/workflows/npm-package-publish.yml
    with:
      package-name: 'react-native-reanimated'
      package-json-path: 'packages/react-native-reanimated/package.json'
      release-type: ${{ github.event_name == 'schedule' && 'nightly' || inputs.release-type || 'nightly' }}
      version: ${{ inputs.version }}
      npm-tag: ${{ inputs.npm-tag }}
      publish: ${{ inputs.publish || false }}
