name: NPM Worklets publish
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    # temporarily trigger on pull_request for testing
    branches:
      - main
  schedule:
    # for nightlies
    - cron: '27 23 * * *' # at 23:27 every day
  workflow_dispatch:
    # for manual publishing
    inputs:
      tag:
        description: NPM dist-tag to publish under.
        required: false
        type: string
        default: latest
      publish_on_npm:
        description: Whether to publish the package on NPM after building or just perform a dry-run.
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write # For publishing on NPM using OIDC

jobs:
  npm-worklets-publish-nightly:
    if: github.repository == 'software-mansion/react-native-reanimated' && github.event_name == 'schedule'
    uses: ./.github/workflows/npm-worklets-package-build.yml
    with:
      option: --nightly
      publish_on_npm: true

  npm-worklets-publish-manual:
    if: github.repository == 'software-mansion/react-native-reanimated'
    uses: ./.github/workflows/npm-worklets-manual-publish.yml
    with:
      tag: ${{ github.event.inputs.tag || 'latest' }}
      publish_on_npm: ${{ github.event.inputs.publish_on_npm || false }}
