name: Reanimated Apple validation
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/reanimated-apple-validation.yml'
      - 'packages/react-native-reanimated/apple/**'
      - 'packages/react-native-reanimated/package.json'
      - 'packages/react-native-reanimated/scripts/validate-apple.sh'
      - 'packages/react-native-reanimated/scripts/cpplint.sh'
      - 'packages/react-native-reanimated/Common/cpp/**'
  pull_request:
    paths:
      - '.github/workflows/reanimated-apple-validation.yml'
      - 'packages/react-native-reanimated/apple/**'
      - 'packages/react-native-reanimated/package.json'
      - 'packages/react-native-reanimated/scripts/validate-apple.sh'
      - 'packages/react-native-reanimated/scripts/cpplint.sh'
      - 'packages/react-native-reanimated/Common/cpp/**'
  merge_group:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install monorepo node dependencies
        run: yarn install --immutable

      - name: Lint apple
        working-directory: packages/react-native-reanimated
        run: yarn lint:apple
