name: Reanimated clang-tidy lint
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    paths:
      - '.github/workflows/reanimated-clang-tidy-lint.yml'
  pull_request:
    paths:
      - '.github/workflows/reanimated-clang-tidy-lint.yml'
  workflow_call:
  workflow_dispatch:

jobs:
  reanimated-clang-tidy-lint:
    if: github.repository == 'software-mansion/react-native-reanimated'
    env:
      REANIMATED_DIR: packages/react-native-reanimated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install monorepo node dependencies
        run: yarn install --immutable
      - name: Build Reanimated package
        working-directory: ${{ env.REANIMATED_DIR }}
        run: yarn build

      - name: Run clang-tidy lint
        working-directory: ${{ env.REANIMATED_DIR }}
        run: yarn lint:clang-tidy
