name: 'Check spelling'
on: [push, pull_request]

jobs:
    spellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: streetsidesoftware/cspell-action@v6
              with:
                files: '**/*.{md,mdx,js,ts,tsx,jsx,json}'
                root: '.'
                config: '.'
                strict: false
                use_cspell_files: false