# checks the spelling of code in all files
name: 'Check spelling'
on:
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: '**/*'
          root: '.'
          config: './cspell.json'
          inline: warning
          strict: true
          use_cspell_files: false
      - name: 'If there are errors'
        run: |
          echo "If there are errors and you think they should not be there, add them to the cspell.json file:"
          echo "{"
          echo "  \"words\": ["
          echo "    \"worklets\","
          echo "    \"worklet\","
          echo "    ... // add your words here"
          echo "  ],"
          echo "}"
        if: ${{ failure() }}

