name: 'Check spelling'
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    spellcheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: streetsidesoftware/cspell-action@v6
              with:
                files: '**/*.{md,mdx,js,ts,tsx,jsx,json}'
                root: '.'
                config: './cspell.json'
                inline: warning
                strict: true
                use_cspell_files: false