name: Static framework Reanimated build check [Nightly]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: 0
on:
  pull_request:
    paths:
      - .github/workflows/static-framework-reanimated-build-nightly.yml
  schedule:
    - cron: '37 19 * * *'
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: macos-14
    strategy:
      matrix:
        react-native-architecture: ['Paper', 'Fabric']
      fail-fast: false
    concurrency:
      group: ios-static-framework-${{ matrix.react-native-architecture }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Create React Native app
        run: npx react-native init app
      - name: Install Reanimated
        working-directory: app
        run: yarn add react-native-reanimated@https://github.com/software-mansion/react-native-reanimated.git#commit=${{ github.sha }}
      - name: Install Paper Pods
        if: ${{ matrix.react-native-architecture == 'Paper' }}
        working-directory: app/ios
        run: export USE_FRAMEWORKS=static NO_FLIPPER=1 && bundle install && bundle exec pod install
      - name: Install Fabric Pods
        if: ${{ matrix.react-native-architecture == 'Fabric' }}
        working-directory: app/ios
        run: export USE_FRAMEWORKS=static NO_FLIPPER=1 RCT_NEW_ARCH_ENABLED=1 && bundle install && bundle exec pod install
      - name: Build app
        working-directory: app
        run: npx react-native run-ios --no-packager
