name: Sync public reanimated

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout szeptem
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches from reanimated repository
        run: |
          git remote add public https://github.com/software-mansion/react-native-reanimated.git
          git fetch public

      - name: Sync all branches
        run: |
          for branch in `git branch -r | grep public/ | grep -v HEAD`; do
            git checkout -B ${branch#public/} $branch
            git push origin ${branch#public/}
          done

      - name: Cleanup
        run: git remote remove public
