name: Validate iOS
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'apple/**'
      - 'package.json'
      - 'scripts/validate-ios.sh'
  pull_request:
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'apple/**'
      - 'package.json'
      - 'scripts/validate-ios.sh'
  merge_group:
    branches:
      - main

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn
      - name: Lint iOS
        run: yarn lint:ios
