name: Validate yarn
env:
  YARN_ENABLE_HARDENED_MODE: 1
on:
  pull_request:
    paths:
      - '.github/workflows/validate-yarn.yml'
      - '**/package.json'
      - '**/yarn.lock'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-yarn.yml'
      - '**/package.json'
      - '**/yarn.lock'

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
      - name: Build package
        run: yarn build

      - name: Get list of updated directories with package.json or yarn.lock
        id: updated_dirs
        run: |
          ECHOLIST=()
          for CHANGE in $(git diff --name-only | grep -E '(package.json|yarn.lock)'); do
            DIR=$(dirname "$CHANGE")
            ECHOLIST+=("$DIR")
          done
          echo "::set-output name=dirList::$(printf '%s\n' "${ECHOLIST[@]}" | sort -u)"
          # print echolist
          echo "dirList: ${ECHOLIST[@]}"
      - name: Perform yarn install in changed directories
        run: |
          for directory in ${{ steps.updated_dirs.outputs.dirList }}
          do
            echo "Yarn install in $directory"
            cd "$directory" && yarn
          done
