name: Validate iOS
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/validate-ios.yml"
      - "packages/react-native-reanimated/apple/**"
      - "packages/react-native-reanimated/package.json"
      - "packages/react-native-reanimated/scripts/validate-ios.sh"
  pull_request:
    paths:
      - ".github/workflows/validate-ios.yml"
      - "packages/react-native-reanimated/apple/**"
      - "packages/react-native-reanimated/package.json"
      - "packages/react-native-reanimated/scripts/validate-ios.sh"
  merge_group:
    branches:
      - main

jobs:
  check:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install monorepo nodedependencies
        run: yarn install
      - name: Install Reanimated node dependencies
        working-directory: packages/react-native-reanimated
        run: yarn install
      - name: Lint iOS
        working-directory: packages/react-native-reanimated
        run: yarn lint:ios
