name: Worklets Apple validation
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/worklets-apple-validation.yml'
      - 'packages/react-native-worklets/apple/**'
      - 'packages/react-native-worklets/package.json'
      - 'packages/react-native-worklets/Common/**'
  pull_request:
    paths:
      - '.github/workflows/worklets-apple-validation.yml'
      - 'packages/react-native-worklets/apple/**'
      - 'packages/react-native-worklets/package.json'
      - 'packages/react-native-worklets/Common/**'
  merge_group:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  worklets-apple-validation:
    if: github.repository == 'software-mansion/react-native-reanimated'
    env:
      WORKLETS_DIR: packages/react-native-worklets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install monorepo node dependencies
        run: yarn install --immutable

      - name: Lint apple
        working-directory: ${{ env.WORKLETS_DIR }}
        run: yarn lint:apple
