name: Worklets Common validation
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/worklets-common-validation.yml'
      - 'packages/react-native-worklets/scripts/cpplint.sh'
      - 'packages/react-native-worklets/scripts/validate-includes.sh'
      - 'packages/react-native-worklets/Common/cpp/**'
  pull_request:
    paths:
      - '.github/workflows/worklets-common-validation.yml'
      - 'packages/react-native-worklets/scripts/cpplint.sh'
      - 'packages/react-native-worklets/scripts/validate-includes.sh'
      - 'packages/react-native-worklets/Common/cpp/**'
  merge_group:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  worklets-common-validation:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    env:
      WORKLETS_DIR: packages/react-native-worklets
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cpplint==1.6.1

      - name: Install monorepo node dependencies
        run: yarn install --immutable

      - name: Lint Common
        working-directory: ${{ env.WORKLETS_DIR }}
        run: yarn lint:common
      - name: Disallow DEBUG macros
        working-directory: ${{ env.WORKLETS_DIR }}
        run: |
          ! egrep -r '(#if DEBUG|#ifdef DEBUG)' Common/cpp/ apple/ android/src/main/cpp/
