name: Worklets Android validation
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
    paths:
      - '.github/workflows/worklets-android-validation.yml'
      - 'packages/react-native-worklets/android/src/**'
      - 'packages/react-native-worklets/android/build.gradle'
      - 'packages/react-native-worklets/Common/**'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/worklets-android-validation.yml'
      - 'packages/react-native-worklets/android/src/**'
      - 'packages/react-native-worklets/android/build.gradle'
      - 'packages/react-native-worklets/Common/**'
  workflow_call:
  workflow_dispatch:

jobs:
  worklets-android-validation:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    concurrency:
      group: worklets-android-validatation-${{ github.ref }}
      cancel-in-progress: true
    env:
      WORKLETS_DIR: packages/react-native-worklets
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        # Using older versions of Java might cause the lint step to throw
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Clear annotations
        run: .github/workflows/helper/clear-annotations.sh

      - name: Install monorepo node dependencies
        run: yarn install --immutable

      - name: Lint Android
        working-directory: ${{ env.WORKLETS_DIR }}
        run: yarn lint:android
