name: Yarn validation
env:
  YARN_ENABLE_HARDENED_MODE: 1
on:
  pull_request:
    paths:
      - '.github/workflows/yarn-validation.yml'
      - '**/package.json'
      - '**/yarn.lock'
  merge_group:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '.github/workflows/yarn-validation.yml'
      - '**/package.json'
      - '**/yarn.lock'
  workflow_call:
  workflow_dispatch:

jobs:
  yarn-validation:
    if: github.repository == 'software-mansion/react-native-reanimated'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install monorepo dependencies
        run: yarn install --immutable

      - name: Check for dependency duplication
        run: yarn dedupe --check
