# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require_relative '../../../scripts/llvm-tools/add-xcode-step.rb'

ENV['IS_REANIMATED_EXAMPLE_APP'] = '1'
ENV['IS_REANIMATED_PROFILING'] = '1'
ENV['IS_WORKLETS_PROFILING'] = '1'


# Using prebuilt React Native iOS binaries for faster builds
# disable if you need to dive in and tweak into React Native native code
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1'
ENV['RCT_USE_RN_DEP'] ||= '1'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'FabricExample.xcodeproj',
        'Debug' => :debug,
        'DebugRuntimeTests' => :debug,
        'Release' => :release

target 'FabricExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    if ENV['USE_CCACHE_LAUNCHER'] == '1'
      ccache_path = `command -v ccache`.strip
      if ccache_path.empty?
        Pod::UI.warn('[Ccache] USE_CCACHE_LAUNCHER=1 but ccache was not found on PATH')
      else
        Pod::UI.puts("[Ccache] Using #{ccache_path} as C_COMPILER_LAUNCHER")
        projects = [installer.pods_project]
        projects += installer.aggregate_targets.map(&:user_project).compact
        projects.uniq { |project| project.path }.each do |project|
          project.build_configurations.each do |config|
            config.build_settings['C_COMPILER_LAUNCHER'] = ccache_path
            config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES_WITH_COMPILER_LAUNCHER'] = 'YES'
          end
          project.save
        end
      end
    end
  end

  add_compile_metadata_step()
end
